[bans]
multiple-versions = "deny"
deny = []
skip-tree = [
    # ignore criterion dev-dependency that often have duplicate dependencies internally
    { name = "criterion" },
    # wasmtime includes multiple versions of hashbrown via cranelift-codegen
    { name = "hashbrown" },
]

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "MIT",
    "MIT-0",
    "Unicode-DFS-2016",
    "Zlib",
]
