[bans]
multiple-versions = "deny"
deny = []
skip-tree = [
    # wasmtime includes multiple versions of rustix via memfd
    { name = "rustix" },
]

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "MIT",
    "MIT-0",
    "Unicode-3.0",
    "Zlib",
]
