[bans]
multiple-versions = "deny"
deny = []
skip-tree = [
    # ignore criterion dev-dependency that often have duplicate dependencies internally
    { name = "criterion" },
    # wasmtime includes multiple versions of hashbrown via cranelift-codegen
    { name = "hashbrown" },
]

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Zlib",
]
