[bans]
multiple-versions = "deny"
deny = []
skip-tree = [
    # ignore criterion dev-dependency that often have duplicate dependencies internally
    { name = "criterion" },
]

[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
]